In [2]:
import numpy as np

In [4]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr.reshape(3,3).flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr.reshape(3,3).ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr.T

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr.reshape(3,3).T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [12]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr.reshape(3,3).transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [15]:
np.argmin(arr)

np.int64(0)

In [16]:
np.argmax(arr)

np.int64(8)

In [17]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.argsort(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [2]:
#Assignment 1: Array Creation and Manipulation

#1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
#2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [28]:
#1
arr = np.random.randint(1,21,25).reshape(5,5)
arr[:,2] = 1
arr

array([[ 2, 14,  1,  6,  8],
       [ 4, 20,  1, 11, 10],
       [ 7, 14,  1,  3, 10],
       [17, 18,  1, 20,  3],
       [15, 11,  1,  8, 10]], dtype=int32)

In [34]:
#2
arr = np.random.randint(1,17,16).reshape(4,4)
np.fill_diagonal(arr,0)
arr

array([[ 0,  5,  5, 15],
       [15,  0, 12,  3],
       [ 2,  1,  0,  5],
       [ 1,  5, 11,  0]], dtype=int32)

In [31]:
#Assignment 2: Array Indexing and Slicing

#1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
#2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [19]:
#1
arr = np.random.randint(1,36,36).reshape(6,6)
arr


array([[17, 17, 11, 34, 27, 31],
       [27, 31, 19,  7, 21, 19],
       [27,  9,  1,  6, 13, 31],
       [26, 24, 10, 16,  5, 23],
       [17,  8,  1, 11, 10, 26],
       [ 3, 31, 15, 25, 12, 29]], dtype=int32)

In [23]:
arr[2:5,1:4]

array([[ 9,  1,  6],
       [24, 10, 16],
       [ 8,  1, 11]], dtype=int32)

In [25]:
#2
arr = np.random.randint(1,100,25).reshape(5,5)
arr

array([[39, 48, 75, 87, 89],
       [ 8, 27, 96,  9, 38],
       [86, 43, 66, 15, 74],
       [80, 18, 79, 64, 82],
       [97, 87, 56, 57, 83]], dtype=int32)

In [26]:
arr[0:,0:6]

array([[39, 48, 75, 87, 89],
       [ 8, 27, 96,  9, 38],
       [86, 43, 66, 15, 74],
       [80, 18, 79, 64, 82],
       [97, 87, 56, 57, 83]], dtype=int32)

In [41]:
### Assignment 3: Array Operations

#1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
#2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [43]:
arr1 = np.random.randint(1,30,12).reshape(3,4)
arr2 = np.random.randint(1,32,12).reshape(3,4)
print('Array 1')
print(arr1)
print('Array 2')
print(arr2)
print('Element wise addition')
arr_sum = arr1+arr2
arr_sum

Array 1
[[ 3 17 14  9]
 [ 1 28 23 12]
 [24 29  6 11]]
Array 2
[[13 25  9 19]
 [30 25 10 19]
 [ 1 10  3 21]]
Element wise addition


array([[16, 42, 23, 28],
       [31, 53, 33, 31],
       [25, 39,  9, 32]], dtype=int32)

In [36]:
arr_sub = arr1-arr2
arr_sub

array([[-19, -12, -10,  11],
       [ 11, -20,  19, -11],
       [-17,  -4, -14,  -4]], dtype=int32)

In [37]:
arr_multiply = arr1*arr2
arr_multiply

array([[ 66, 493, 551, 522],
       [102,  96,  42,  26],
       [ 84, 165, 275,  96]], dtype=int32)

In [38]:
arr1/arr2

array([[ 0.13636364,  0.5862069 ,  0.65517241,  1.61111111],
       [ 2.83333333,  0.16666667, 10.5       ,  0.15384615],
       [ 0.19047619,  0.73333333,  0.44      ,  0.66666667]])

In [44]:
#2
arr = np.random.randint(1,16,16).reshape(4,4)
arr

array([[14,  7, 13, 15],
       [12, 11,  7, 13],
       [10,  2, 10, 11],
       [11,  3,  4,  2]], dtype=int32)

In [45]:
row_sum = np.sum(arr,axis = 1)
row_sum

array([49, 43, 33, 20])

In [46]:
col_sum = np.sum(arr,axis = 0)
col_sum

array([47, 23, 34, 41])

In [56]:
### Assignment 4: Statistical Operations

#1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
#2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [47]:
arr = np.random.randint(1,100,25).reshape(5,5)
arr

array([[11, 59, 67, 14, 81],
       [20, 41, 82, 64, 52],
       [53, 95, 46, 80, 10],
       [27, 22, 77, 38, 36],
       [63, 39, 72, 45, 99]], dtype=int32)

In [48]:
np.mean(arr)


np.float64(51.72)

In [49]:
np.median(arr)



np.float64(52.0)

In [50]:
np.std(arr)


np.float64(25.621116291059607)

In [51]:
np.var(arr)

np.float64(656.4416)

In [52]:
#2
arr = np.random.randint(1,10,9).reshape(3,3)
arr

array([[8, 4, 2],
       [2, 2, 7],
       [9, 5, 6]], dtype=int32)

In [56]:
mean = np.mean(arr)
mean


np.float64(5.0)

In [57]:
std_dev = np.std(arr)
std_dev

np.float64(2.5385910352879693)

In [58]:
#Normalized array
normalized_array = (arr-mean)/std_dev
normalized_array

array([[ 1.1817579 , -0.3939193 , -1.1817579 ],
       [-1.1817579 , -1.1817579 ,  0.7878386 ],
       [ 1.57567719,  0.        ,  0.3939193 ]])

In [67]:
### Assignment 5: Broadcasting

#1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
#2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [59]:
#1
arr = np.random.randint(1,20,9).reshape(3,3)
arr

array([[13, 10,  3],
       [14,  2,  7],
       [ 5, 15,  5]], dtype=int32)

In [60]:
arr1 = np.random.randint(1,4,3).reshape(3,)
arr1

array([2, 1, 1], dtype=int32)

In [62]:
arr2 = arr+arr1
arr2

array([[15, 11,  4],
       [16,  3,  8],
       [ 7, 16,  6]], dtype=int32)

In [63]:
#2
arr = np.random.randint(1,20,16).reshape(4,4)
arr

array([[ 7,  4,  5, 12],
       [17, 11, 18,  3],
       [10, 13,  1, 16],
       [ 5, 11,  7,  3]], dtype=int32)

In [66]:
column_arr1 = np.random.randint(1,4,4).reshape(4,)
column_arr1

array([2, 1, 2, 2], dtype=int32)

In [69]:
arr2 = arr-column_arr1[:, np.newaxis] 
arr2

array([[ 5,  2,  3, 10],
       [16, 10, 17,  2],
       [ 8, 11, -1, 14],
       [ 3,  9,  5,  1]], dtype=int32)

In [78]:
### Assignment 6: Linear Algebra

#1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
#2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.


In [79]:
### Assignment 7: Advanced Array Manipulation

#1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
#2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [84]:
#1
arr = np.random.randn(1,9).reshape(3,3)
arr

array([[ 0.29841224,  0.35326699,  0.6277747 ],
       [ 0.07546159, -0.14065528,  1.14473711],
       [-1.3641689 , -1.06514978,  0.96131661]])

In [82]:
arr.reshape(1,9)

array([[ 0.08965881,  1.31395792,  0.27412073,  0.12308793, -0.20108804,
         0.52110178,  0.42575879,  0.6042235 ,  0.68387851]])

In [83]:
arr.reshape(9,1)

array([[ 0.08965881],
       [ 1.31395792],
       [ 0.27412073],
       [ 0.12308793],
       [-0.20108804],
       [ 0.52110178],
       [ 0.42575879],
       [ 0.6042235 ],
       [ 0.68387851]])

In [85]:
#2
arr = np.random.randn(1,25).reshape(5,5)
arr

array([[-7.39944002e-01, -1.08390935e+00,  1.35551446e+00,
        -7.54828660e-01, -1.23745746e+00],
       [-2.96797242e-01, -1.65516118e+00,  6.88370268e-05,
        -8.17768409e-01, -8.07012562e-01],
       [ 1.75169501e+00, -1.94612736e+00,  1.20746111e+00,
        -1.05307846e+00,  1.43255840e+00],
       [-5.54267972e-01,  5.71417772e-01,  6.47182882e-01,
        -2.71376195e-01, -7.54465865e-01],
       [ 1.11568753e+00,  1.19266277e-01, -1.91229492e-01,
         4.62351139e-02,  3.79454860e-01]])

In [86]:
arr.flatten()

array([-7.39944002e-01, -1.08390935e+00,  1.35551446e+00, -7.54828660e-01,
       -1.23745746e+00, -2.96797242e-01, -1.65516118e+00,  6.88370268e-05,
       -8.17768409e-01, -8.07012562e-01,  1.75169501e+00, -1.94612736e+00,
        1.20746111e+00, -1.05307846e+00,  1.43255840e+00, -5.54267972e-01,
        5.71417772e-01,  6.47182882e-01, -2.71376195e-01, -7.54465865e-01,
        1.11568753e+00,  1.19266277e-01, -1.91229492e-01,  4.62351139e-02,
        3.79454860e-01])

In [87]:
arr.reshape(5,5)

array([[-7.39944002e-01, -1.08390935e+00,  1.35551446e+00,
        -7.54828660e-01, -1.23745746e+00],
       [-2.96797242e-01, -1.65516118e+00,  6.88370268e-05,
        -8.17768409e-01, -8.07012562e-01],
       [ 1.75169501e+00, -1.94612736e+00,  1.20746111e+00,
        -1.05307846e+00,  1.43255840e+00],
       [-5.54267972e-01,  5.71417772e-01,  6.47182882e-01,
        -2.71376195e-01, -7.54465865e-01],
       [ 1.11568753e+00,  1.19266277e-01, -1.91229492e-01,
         4.62351139e-02,  3.79454860e-01]])

In [88]:
### Assignment 8: Fancy Indexing and Boolean Indexing

#1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
#2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.


In [17]:
#1 
arr=np.random.randint(1,100,25).reshape(5,5)
arr

array([[58, 94, 96, 53, 91],
       [67, 31, 29, 15, 46],
       [81, 53, 12,  8, 64],
       [32, 95, 17, 95, 99],
       [55, 54,  2, 20, 83]], dtype=int32)

In [18]:
corners = arr[[0,0,-1,-1],[0,-1,0,-1]]
print('Corner Elements')
corners

Corner Elements


array([58, 91, 55, 83], dtype=int32)

In [10]:
#2
arr=np.random.randn(1,16).reshape(4,4)
arr

array([[ 0.44861013, -0.22853382,  1.17706689, -1.07588769],
       [-0.30185497,  0.50114146, -0.32207658,  0.20170438],
       [ 0.43546963, -1.3969681 ,  0.04851124, -0.64333996],
       [-0.87296917, -2.09503912, -0.16191307,  0.52567656]])

In [15]:
# Create a NumPy array of shape (4, 4) filled with random integers
array = np.random.randint(1, 21, 16).reshape(4,4)
print("Original array:")
print(array)


Original array:
[[ 5 15 16  7]
 [ 7  6 18 20]
 [20 10 19  7]
 [15 14 17  8]]


In [16]:
array[array>10] = 10
array

array([[ 5, 10, 10,  7],
       [ 7,  6, 10, 10],
       [10, 10, 10,  7],
       [10, 10, 10,  8]], dtype=int32)

In [11]:
### Assignment 9: Structured Arrays

#1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
#2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [90]:
### Assignment 10: Masked Arrays

#1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
#2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.